### PR TITLE
Rust warpshell v2

### PR DESCRIPTION
**Pull request by vkomenda**
- [X] convenient helpers for memory-mapped cores (`GetDmaChannel`, `GetCtrlChannel`, `BaseParam`)
  - [X] their integration into the Std shell
  - [X] reduced boilerplate impls thanks to procmacros
- [X] renamed the library crate to `warpshell` and reset the version to 0.1.0
- [X] barebones AXI firewall core
- [X] HBICAP core
  - [X] skeleton Ops trait and integration with the Std shell
  - [X] working examples or benchmarks
- [X] CLI binary (separate crate in `rust/`)
- [X] merge v2 bitstream and scripts
- [ ] update docs about flashing
  - [ ] xbflash2
  - [ ] standalone compilation instructions for xbflash2 without the rest of XRT

### CODE REVIEW

**Comment by Quarky93** [comment]
Wow! Looks good!

**Comment by Quarky93** [comment]
Did you successfully load a user.bin using this new HBICAP driver?

**Comment by vkomenda** [comment]
Not yet as I'm away from the machine but I can try remotely hoping it
wouldn't crash. I can't boot it back up when I'm not in 🤷

**Comment by Quarky93** [comment]
I've 'merged' (it was messy so I just committed the changed parts as new) warpshell-v2 back into main.
I guess we are ready for the new rust driver to be merged :grin: .

**Comment by vkomenda** [comment]
> I've 'merged' (it was messy so I just committed the changed parts as new) warpshell-v2 back into main. I guess we are ready for the new rust driver to be merged grin .

Thanks! We'll add flashing instructions a bit later then.

**Pull request merged**
